### ISSUE TITLE
support line number?

### ISSUE THREAD

**Issue by JSerZANP** [JSerZANP/shaku#56]

**Comment by Seven-Y-Q-Guo** [comment]
It should be part of shiki, but after checking this functionality is not supported natively.
I found one solution related to line number is pretty good:
https://github.com/shikijs/shiki/issues/3#issuecomment-830564854
```css
code {
  counter-reset: step;
  counter-increment: step 0;
}

code .line::before {
  content: counter(step);
  counter-increment: step;
  width: 1rem;
  margin-right: 1.5rem;
  display: inline-block;
  text-align: right;
  color: rgba(115,138,148,.4)
}
```
